# Generated by Django 2.1.4 on 2019-02-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(max_length=200)),
                ('HOD', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(default='', max_length=150, unique=True)),
                ('Employed_On', models.DateTimeField(auto_now=True)),
                ('Specialization', models.CharField(default='', max_length=150, unique=True)),
                ('Sex', models.CharField(default='', max_length=7, unique=True)),
                ('Phone_Number', models.CharField(default='', max_length=12, unique=True)),
                ('Address', models.CharField(default='', max_length=100, unique=True)),
                ('Qualification', models.CharField(default='', max_length=256)),
                ('Location', models.CharField(default='', max_length=256)),
                ('Doctor_Department', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='department', to='hro.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(default='', max_length=256)),
                ('DOB', models.DateField()),
                ('Phone_Number', models.CharField(max_length=13)),
                ('Age', models.CharField(default='', max_length=200, unique=True)),
                ('Address', models.CharField(max_length=256)),
                ('Symptom', models.CharField(default='', max_length=256)),
                ('Date_Reported_Sick', models.DateField()),
                ('Refer_to_Doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patientsRefName', to='hro.Doctor')),
            ],
        ),
    ]
